### PR TITLE
intuos4 large support

### PR DESCRIPTION
**Pull request by lokkiikkol**
added intuos4 large support, the old-fashioned way, feel free to not accept, if you want to go the table way :)

### CODE REVIEW

**Comment by KurtE** [comment]
It is merged,  There was one conflict, where I added a different tablet earlier, so updated it up on github,
Probably should check if it still builds

**Comment by KurtE** [comment]
Looks like you undid all of my stuff for Intuos S 4100 stuff, working on merging it back in.

**Comment by lokkiikkol** [comment]
sorry, so much! i think i worked on an old version and pushed that…

the version you merged builds here (and works) after i add 

INTUOS4100 to the 

enum {
	PENPARTNER = 0,
	INTUOS5S,
	INTUOS5,
	INTUOS5L,
  	INTUOS4L,
  	INTUOS4100,
	BAMBOO_PEN,
	INTUOSHT,
	INTUOSHT2,
	BAMBOO_TOUCH,
	BAMBOO_PT,
	WACOM_24HDT,
	WACOM_27QHDT,
	BAMBOO_PAD,
	H640P,
	MAX_TYPE,
};

**Comment by lokkiikkol** [comment]
still works after your last commit (intuos 4100 back in). sorry again.

**Pull request merged**
